common_data_io: &defaults
  train: # Bad naming but this is used to generate batch size of examples from iterator
    batch_size: 8
  data:
    num_parallel_reads: 4
    inputs:
      # Ensure, this key is the same the model.tensor_dict
      x_dm:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 5 # (X, Y, Z, i, Zcam_normed)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_dm'
      x_cam:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 3   # (R, G, B)   (0, 255.)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_cam'

      x_R_rects:
        modality: 'matrix'
        data_type: 'float32'
        shape: [3, 3]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_R_rects'

      x_P_rects:
        modality: 'matrix'
        data_type: 'float32'
        shape: [3, 4]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_P_rects'

      y_dm:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 5
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'y_dm'

      y_se3param:
        modality: 'vector'
        data_type: 'float32'
        shape: [6]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'y_se3param'

    # Below are configs for tfrecords files
    compression_type: '' # no compression
    suffix: 'tfrecord'
    tfrecords_test_dirs:
      - "kitti/tfrecords/test/T1"
      - 'kitti/tfrecords/test/T2a'
      - "kitti/tfrecords/test/T2b"
      - "kitti/tfrecords/test/T3"


rggnet:
  <<: *defaults
  pb_fp: 'prod_64/rggnet/eps1.pb'
  tensors:
    inputs:
    - 'rggnet/Placeholders/x_dm:0'
    - 'rggnet/Placeholders/x_cam:0'
    outputs:
    - 'rggnet/Forward/Regressor/y_hat_se3param:0'

rggnet_3dstn:
  <<: *defaults
  pb_fp: 'prod/rggnet_3dstn/best.pb'
  tensors:
    inputs:
    - 'rggnet_3dstn/Placeholders/x_dm:0'
    - 'rggnet_3dstn/Placeholders/x_cam:0'
    outputs:
    - 'rggnet_3dstn/Forward/Regressor/y_hat_se3param:0'

rggnet_novae:
  <<: *defaults
  pb_fp: 'prod/rggnet_novae/best.pb'
  tensors:
    inputs:
    - 'rggnet_novae/Placeholders/x_dm:0'
    - 'rggnet_novae/Placeholders/x_cam:0'
    outputs:
    - 'rggnet_novae/Forward/Regressor/y_hat_se3param:0'

rggnet_plus:
  <<: *defaults
  pb_fp: 'prod/rggnet_plus/best.pb'
  tensors:
    inputs:
    - 'rggnet/Placeholders/x_dm:0'
    - 'rggnet/Placeholders/x_cam:0'
    outputs:
    - 'rggnet/Forward/Regressor/y_hat_se3param:0'
