common_data_io: &defaults
  train: # Bad naming but this is used to generate batch size of examples from iterator
    batch_size: 8
  data:
    num_parallel_reads: 4
    inputs:
      # Ensure, this key is the same the model.tensor_dict
      x_dm:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 5 # (X, Y, Z, i, Zcam_normed)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_dm'
      x_cam:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 3   # (R, G, B)   (0, 255.)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_cam'
      r_x_dm:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 5 # (X, Y, Z, i, Zcam_normed)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'r_x_dm'
      r_x_cam:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 3   # (R, G, B)   (0, 255.)
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'r_x_cam'

      x_R_rects:
        modality: 'matrix'
        data_type: 'float32'
        shape: [3, 3]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_R_rects'

      x_P_rects:
        modality: 'matrix'
        data_type: 'float32'
        shape: [3, 4]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'x_P_rects'

      y_dm:
        modality: 'image'
        data_type: 'float32'
        nhwc: True
        H: 375
        W: 1242
        C: 5
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'y_dm'

      y_se3param:
        modality: 'vector'
        data_type: 'float32'
        shape: [6]
        # Feature listed below will be random chosen on the fly
        feature_names:
          - 'y_se3param'

    # Below are configs for tfrecords files
    compression_type: '' # no compression
    suffix: 'tfrecord'
    tfrecords_test_dirs:
      - "/root/kitti-raw/test_stereo/T1"

stereo_rggnet_novae:
  <<: *defaults
  pb_fp: 'prod/stereo_rggnet_novae_50/best.pb'
  tensors:
    inputs:
    - 'stereorggnet_novae/Placeholders/x_dm:0'
    - 'stereorggnet_novae/Placeholders/x_cam:0'
    - 'stereorggnet_novae/Placeholders/r_x_dm:0'
    - 'stereorggnet_novae/Placeholders/r_x_cam:0'
    outputs:
    - 'stereorggnet_novae/y_hat_se3param:0'
    compression_type: '' # no compression
    suffix: 'tfrecord'
    tfrecords_test_dirs:
      - "/root/kitti-raw/test_stereo/T1"
