#The training data serialization process is totally configurable.
#To create your own training data, just adding a similar block with the template
#training_data:
#  number: ${number}
#  reduce_lidar_line_to: ${lidar_number}       # Shall be 8, 16, 32, 64
#  raw_data_dir: '/root/kitti/raw/train'             # Replace with your own path
#  output_data_dir: '/root/kitti/tfrecords_16/train' # Replace with your own path
#  vae_resized:
#    H: 160
#    W: 640
#  off_range:
#    rot: ${rot_range}        # deg
#    trans: ${trans_range}    # m

# (09/26/2011 0005/0007)
T1:
  number: 2000
  reduce_lidar_line_to: 16
  output_format: 'tfrecords'
  raw_data_dir: '/mnt/disks/kitti-dataset/test'
  output_data_dir: '/mnt/disks/kitti-dataset/tfrecords_16/test/T1'
  vae_resized:
    H: 160
    W: 640
  off_range:
    rot: 15        # deg
    trans: 0.2     # m

# # (09/26/2011 0005/0007)
# T2a:
#   number: 2000
#   reduce_lidar_line_to: 16
#   output_format: 'tfrecords'
#   raw_data_dir: '/mnt/disks/kitti-dataset/test'
#   output_data_dir: '/mnt/disks/kitti-dataset/tfrecords_16/test/T2a'
#   vae_resized:
#     H: 160
#     W: 640
#   off_range:
#     rot: 10        # deg
#     trans: 0.2     # m

# # (09/26/2011 0005/0007)
# T2b:
#   number: 2000
#   reduce_lidar_line_to: 16
#   output_format: 'tfrecords'
#   raw_data_dir: '/root/kitti/raw/test'
#   output_data_dir: '/root/kitti/tfrecords_16/test/T2b'
#   vae_resized:
#     H: 160
#     W: 640
#   off_range:
#     rot: 10        # deg
#     trans: 0.2     # m

# # (09/26/2011 0005/0007)
# #| T3 | 2000 (03_10, 0027) |  52 GB|+/- 2 deg| +/- 0.3 m|
# T3:
#   force_shape: # due to a different drive
#     H: 375
#     W: 1242
#   number: 2000
#   reduce_lidar_line_to: 16
#   output_format: 'tfrecords'
#   raw_data_dir: '/root/kitti/raw/T4'
#   output_data_dir: '/root/kitti/tfrecords_16/test/T3'
#   vae_resized:
#     H: 160
#     W: 640
#   off_range:
#     rot: 2        # deg
#     trans: 0.3     # m
