#The training data serialization process is totally configurable.
#To create your own training data, just adding a similar block with the template
#training_data:
#  number: ${number}
#  reduce_lidar_line_to: ${lidar_number}       # Shall be 8, 16, 32, 64
#  raw_data_dir: '/root/kitti/raw/train'             # Replace with your own path
#  output_data_dir: '/root/kitti/tfrecords_16/train' # Replace with your own path
#  vae_resized:
#    H: 160
#    W: 640
#  off_range:
#    rot: ${rot_range}        # deg
#    trans: ${trans_range}    # m

training_data_trans_only:
  number: 4000
  reduce_lidar_line_to: 16
  raw_data_dir: '/mnt/disks/kitti-dataset/train'
  output_data_dir: '/mnt/disks/kitti-train/tfrecords_16/train/trans'
  vae_resized:
    H: 160
    W: 640
  off_range:
    rot: 0.00001        # deg
    trans: 0.3          # m

training_data_rot_only:
  number: 4000
  reduce_lidar_line_to: 16
  raw_data_dir: '/mnt/disks/kitti-dataset/train'
  output_data_dir: '/mnt/disks/kitti-train/tfrecords_16/train/rot'
  vae_resized:
    H: 160
    W: 640
  off_range:
    rot: 20            # deg
    trans: 0.00001     # m
